### ISSUE TITLE
Kapot

### ISSUE THREAD

**Issue by RendallSchijven** [midje/feedback#3]
Waar is de wc?

**Comment by janyksteenbeek** [comment]
@mirkokroese kan jij deze oppakken?

**Comment by mirkokroese** [comment]
@janyksteenbeek Ik zeg wontfix, sorry.

**Comment by mirkokroese** [comment]
Misschien deze even bij @pieterhielkema neerleggen?

**Comment by pieterhielkema** [comment]
Ik was hier nog niet klaar mee
